# Generated by Django 4.2.5 on 2023-09-27 20:45

from django.db import migrations

INIT_DATA = [
    {
      "name": "BASIC",
      "save_original": False,
      "generate_expiring_link": False,
      "thumbnail_sizes": [200]
    },
    {
      "name": "ENTERPRISE",
      "save_original": True,
      "generate_expiring_link": True,
      "thumbnail_sizes": [200, 400]
    },
    {
      "name": "PREMIUM",
      "save_original": True,
      "generate_expiring_link": True,
      "thumbnail_sizes": [200, 400]
    }
]

def init_populate(apps, schema_editor):
    UserTier = apps.get_model("ImageAPI", "UserTier")
    for tier in INIT_DATA:
        UserTier(**tier).save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_populate)
    ]
