# Generated by Django 4.2.5 on 2023-09-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0002_alter_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertier',
            name='max_expire_seconds',
            field=models.PositiveIntegerField(default=30000, null=True),
        ),
        migrations.AddField(
            model_name='usertier',
            name='min_expire_seconds',
            field=models.PositiveIntegerField(default=300, null=True),
        ),
    ]
