# Generated by Django 4.2.5 on 2023-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0004_alter_usertier_max_expire_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertier',
            name='thumbnail_sizes',
            field=models.JSONField(default={'resolution': []}),
        ),
    ]
