# Generated by Django 4.2.5 on 2023-09-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0005_alter_usertier_thumbnail_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertier',
            name='thumbnail_sizes',
            field=models.JSONField(default=dict),
        ),
    ]
