# Generated by Django 4.2.5 on 2023-09-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0007_alter_usertier_thumbnail_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImageAPI.usertier'),
        ),
    ]
