# Generated by Django 4.2.5 on 2023-09-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0008_alter_user_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnails',
            field=models.JSONField(default=list, null=True),
        ),
    ]
