# Generated by Django 4.2.5 on 2023-09-25 19:05

import ImageAPI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0010_alter_image_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=ImageAPI.models.Image.image_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnails',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to=ImageAPI.models.Thumbnail.thumbnail_path)),
                ('original_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ImageAPI.image')),
            ],
        ),
    ]
