# Generated by Django 4.2.5 on 2023-09-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0012_remove_image_thumbnails_alter_image_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='height',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
