# Generated by Django 4.2.5 on 2023-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageAPI', '0013_thumbnail_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
